const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

export function fmtSize(bytes) {
  if (bytes === 0) return "0 B";
  if (!bytes && bytes !== 0) return "–";
  const units = ["B", "KB", "MB", "GB", "TB"];
  const i = Math.min(units.length - 1, Math.floor(Math.log(bytes) / Math.log(1024)));
  const v = bytes / 1024 ** i;
  return `${v >= 100 ? v.toFixed(0) : v.toFixed(1)} ${units[i]}`;
}

function heat(ratio) {
  const stops = [
    [0.9, "#1d4ed8"],
    [0.75, "#2563eb"],
    [0.5, "#0891b2"],
    [0.25, "#059669"],
    [0.1, "#ca8a04"],
    [0, "#dc2626"],
  ];
  for (const [t, c] of stops) {
    if (ratio >= t * 0.999 || t === 0) return c;
  }
  return "#64748b";
}

export function renderHtml({ tree, warnings = [], topFiles = [], meta = {} }) {
  const data = JSON.stringify(prune(tree));
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>disk-hog — ${esc(tree.name)}</title>
<style>
  :root { --bg:#0f172a; --panel:#1e293b; --text:#e2e8f0; --muted:#94a3b8; --border:#334155; }
  * { box-sizing:border-box; }
  body { margin:0; font-family:ui-sans-serif,system-ui,"Segoe UI",Roboto,sans-serif; background:var(--bg); color:var(--text); }
  header { padding:14px 20px; display:flex; flex-wrap:wrap; gap:8px 24px; align-items:baseline; border-bottom:1px solid var(--border); background:var(--panel); }
  header h1 { margin:0; font-size:18px; font-weight:600; }
  header .stat { color:var(--muted); font-size:13px; }
  header .stat b { color:var(--text); }
  #crumbs { padding:10px 20px 4px; font-size:13px; color:var(--muted); min-height:22px; }
  #crumbs a { color:#60a5fa; cursor:pointer; text-decoration:none; margin-right:6px; }
  #crumbs a:hover { text-decoration:underline; }
  svg { display:block; width:calc(100vw - 40px); height:70vh; margin:6px 20px; background:#111826; border:1px solid var(--border); border-radius:10px; }
  rect.cell { stroke:#0f172a; stroke-width:1; cursor:pointer; transition:opacity .12s; }
  rect.cell:hover { opacity:.82; }
  rect.cell.dir { cursor:pointer; }
  rect.cell.file { cursor:default; }
  text.lbl { fill:#fff; pointer-events:none; font-size:12px; font-family:inherit; }
  text.sub { fill:rgba(255,255,255,.72); pointer-events:none; font-size:10px; font-family:inherit; }
  h2 { font-size:15px; margin:18px 20px 8px; }
  table { border-collapse:collapse; margin:0 20px 24px; width:calc(100vw - 40px); }
  th, td { text-align:left; padding:6px 12px; border-bottom:1px solid var(--border); font-size:13px; }
  th { color:var(--muted); text-transform:uppercase; font-size:11px; letter-spacing:.05em; }
  td.num { text-align:right; font-variant-numeric:tabular-nums; }
  .bar { height:10px; background:#2563eb; border-radius:3px; }
  footer { padding:8px 20px 28px; color:var(--muted); font-size:12px; }
  #warns { margin:0 20px; color:#fbbf24; font-size:12px; }
</style>
</head>
<body>
<header>
  <h1>disk-hog · ${esc(tree.name)}</h1>
  <span class="stat">total <b>${fmtSize(tree.size)}</b></span>
  <span class="stat"><b>${(tree.fileCount ?? 0).toLocaleString()}</b> files</span>
  <span class="stat"><b>${(tree.dirCount ?? 0).toLocaleString()}</b> folders</span>
  <span class="stat">scanned ${esc(meta.scannedAt ?? "")}</span>
</header>
${warnings.length ? `<p id="warns">${warnings.length} warning(s), e.g. ${esc(warnings[0])}</p>` : ""}
<div id="crumbs"></div>
<svg id="map" preserveAspectRatio="none"></svg>
<h2>Largest files</h2>
<table><thead><tr><th>#</th><th>file</th><th style="text-align:right">size</th><th style="width:34%"></th></tr></thead><tbody>
${topFiles
  .map(
    (f, i) => `<tr>
      <td>${i + 1}</td>
      <td class="mono" title="${esc(f.path)}">${esc(f.path.length > 90 ? "..." + f.path.slice(-87) : f.path)}</td>
      <td class="num">${fmtSize(f.size)}</td>
      <td><div class="bar" style="width:${Math.max(1, (f.size / Math.max(topFiles[0].size, 1)) * 100).toFixed(1)}%"></div></td>
    </tr>`
  )
  .join("\n")}
</tbody></table>
<footer>Generated by <a style="color:#60a5fa" href="https://github.com/trenysx/disk-hog">disk-hog</a> — self-contained report, works offline.</footer>
<script>
const DATA = ${data};
const svg = document.getElementById('map');
const crumbs = document.getElementById('crumbs');

function fmt(b){ if(!b) return '0 B'; const u=['B','KB','MB','GB','TB']; const i=Math.min(u.length-1,Math.floor(Math.log(b)/Math.log(1024))); const v=b/1024**i; return (v>=100?v.toFixed(0):v.toFixed(1))+' '+u[i]; }
function heat(ratio){ const stops=[[0.9,'#1d4ed8'],[0.75,'#2563eb'],[0.5,'#0891b2'],[0.25,'#059669'],[0.1,'#ca8a04'],[0,'#dc2626']]; for(const [t,c] of stops){ if(ratio>=t*0.999||t===0) return c; } return '#64748b'; }

function squarify(items,x,y,w,h){
  const total=items.reduce((a,b)=>a+b.value,0);
  const out=[];
  if(total<=0||w<=0||h<=0) return out;
  let rem=items.filter(i=>i.value>0).sort((a,b)=>b.value-a.value);
  let cx=x,cy=y,cw=w,ch=h,areaLeft=w*h,valueLeft=total;
  while(rem.length&&areaLeft>0&&cw>0.5&&ch>0.5){
    const vert=cw<ch, side=vert?ch:cw;
    const row=[]; let rowVal=0,best=Infinity;
    for(const it of rem){
      const cand=rowVal+it.value;
      const rowArea=cand/valueLeft*areaLeft;
      const th=rowArea/side;
      const all=[...row,it];
      let worst=th<=0?Infinity:0;
      for(const r of all){ const len=(r.value/cand)*rowArea/th; worst=Math.max(worst,len<=0?Infinity:Math.max(len/th,th/len)); }
      if(!row.length||worst<=best){row.push(it);rowVal=cand;best=worst;}else break;
    }
    const rowArea=rowVal/valueLeft*areaLeft, th=rowArea/side;
    let off=0;
    for(const it of row){ const len=(it.value/rowVal)*rowArea/th;
      if(vert) out.push({...it,x:cx,y:cy+off,w:th,h:len}); else out.push({...it,x:cx+off,y:cy,w:len,h:th});
      off+=len; }
    if(vert){cx+=th;cw-=th;}else{cy+=th;ch-=th;}
    areaLeft-=rowArea; valueLeft-=rowVal; rem=rem.slice(row.length);
  }
  return out;
}
const NS='http://www.w3.org/2000/svg';
function nodeValue(n){ return n.size||0; }
function render(node){
  svg.innerHTML='';
  crumbs.innerHTML='';
  const chain=[]; (function find(root,target){ if(root===target){chain.push(root);return true;} for(const c of root.children||[]) if(find(c,target)){chain.unshift(root);return true;} return false; })(DATA,node);
  chain.forEach((n,i)=>{
    if(i>0){const s=document.createElementNS(NS,'text');s.textContent=' / ';s.setAttribute('fill','#475569');crumbs.appendChild(s);}
    const a=document.createElement('a');a.textContent=n.name;a.onclick=()=>render(n);crumbs.appendChild(a);
  });
  const W=Math.max(100,svg.clientWidth||1200), H=Math.max(80,svg.clientHeight||600);
  svg.setAttribute('viewBox','0 0 '+W+' '+H);
  const items=node.children.map(c=>({node:c,value:c.size||0}));
  const rects=squarify(items,1,1,W-2,H-2);
  const maxV=Math.max(...items.map(i=>i.value),1);
  for(const r of rects){
    const n=r.node, isDir=(n.children&&n.children.length>0)||n.truncated||n.dirCount>0;
    const g=document.createElementNS(NS,'g');
    const rect=document.createElementNS(NS,'rect');
    rect.setAttribute('x',r.x.toFixed(1));rect.setAttribute('y',r.y.toFixed(1));
    rect.setAttribute('width',Math.max(1,r.w).toFixed(1));rect.setAttribute('height',Math.max(1,r.h).toFixed(1));
    rect.setAttribute('rx',3);
    rect.setAttribute('class','cell '+(isDir?'dir':'file'));
    rect.setAttribute('fill',heat((n.size||0)/maxV));
    const title=document.createElementNS(NS,'title');
    title.textContent=n.name+' — '+fmt(n.size)+(isDir?' ('+(n.fileCount||0)+' files)':'');
    g.appendChild(title);
    g.appendChild(rect);
    if(r.w>52&&r.h>30){
      const t=document.createElementNS(NS,'text');t.setAttribute('class','lbl');
      t.setAttribute('x',(r.x+6).toFixed(1));t.setAttribute('y',(r.y+16).toFixed(1));
      let name=n.name; const maxCh=Math.floor((r.w-12)/6.6);
      if(name.length>maxCh) name=name.slice(0,Math.max(1,maxCh-1))+'…';
      t.textContent=name; g.appendChild(t);
      if(r.h>46){ const s=document.createElementNS(NS,'text');s.setAttribute('class','sub');
        s.setAttribute('x',(r.x+6).toFixed(1));s.setAttribute('y',(r.y+30).toFixed(1));
        s.textContent=fmt(n.size)+(isDir?' · '+(n.fileCount||0)+' files':''); g.appendChild(s); }
    }
    if(isDir) g.addEventListener('click',()=>render(n));
    svg.appendChild(g);
  }
}
window.addEventListener('resize',()=>render(current||DATA));
let current=null;
const _render=render; render=function(n){current=n;_render(n);};
render(DATA);
</script>
</body>
</html>`;
}

function prune(node) {
  const copy = {
    name: node.name,
    size: node.size,
    fileCount: node.fileCount,
    dirCount: node.dirCount,
  };
  if (node.inaccessible) copy.inaccessible = true;
  if (node.truncated) copy.truncated = true;
  if (node.children?.length) {
    copy.children = node.children
      .slice(0, 200)
      .map(prune)
      .filter((c) => c.size > 0);
  }
  return copy;
}
